name: Add a book to a topic

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        description: "title for the new book"
        required: true
      image_url:
        type: string
        description: "image url"
        required: true
      topic:
        type: string
        description: "given topic"
        required: true

jobs:
  scaffold_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ::set-output name=lowerCase::$(cat README.md | tr '[:upper:]' '[:lower:]')
        id: readme
      - run: echo ::set-output name=lowerCaseWithMdHeader::$(echo "### ${{ github.event.inputs.topic }}" | tr '[:upper:]' '[:lower:]')
        id: topic
      - run: echo ::set-output name=lowerCaseUnderscore::$(echo "${{ github.event.inputs.title }}" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')
        id: title

      - if: ${{ !contains(steps.readme.outputs.lowerCase, steps.topic.outputs.lowerCaseWithMdHeader) }}
        run: |-
          cat >> README.md <<EOF
          
          ### ${{ github.event.inputs.topic }}
          | Cover         | Title         | Link  |
          | ------------- |:-------------:| -----:|
          EOF

      - run: |-
          cat >> README.md <<EOF
  
          | ![${{steps.title.outputs.lowerCaseUnderscore }}](${{steps.title.outputs.lowerCaseUnderscore }}/cover.jpg) | ${{ github.event.inputs.title }} | [key takeaways](${{steps.title.outputs.lowerCaseUnderscore }}/takeaways.md) |
          EOF

      - run: wget -O ./${{steps.title.outputs.lowerCaseUnderscore }}/cover.jpg ${{ github.event.inputs.image_url }}"
      - run: |-
          cat > ./${{steps.title.outputs.lowerCaseUnderscore }}/takeaways.md <<EOF
          ![cover](cover.jpg)
        
          ### ${{ github.event.inputs.title }}
          EOF
      - run: |
          git config --global user.name 'Stefan Breitenstein'
          git config --global user.email 'ste-xx@users.noreply.github.com'
          git commit -am "Add entry: ${{ github.event.inputs.title }} in ${{ github.event.inputs.topic }}"
          git push
#      - run: "if header not exists: add header, add table (| Cover         | Title         | Link  |)"
#      - run: "transform title to lowercase_snakecase "
#      - run: "add entry to header/table (transformed_title/cover.jpg | title | transformed_title/takeaways.md)"
#      - run: "wget image_url -> transformed_title/cover.jpg"
#      - run: "create transformed_title/takeaways.md"